#!/bin/bash
cd /home/rocky/nhstory
echo Pulling latest code...
git pull origin main
echo Installing dependencies...
npm install
echo Building...
npm run build
echo Restarting server...
pm2 restart nhstory
pm2 save
echo Deploy complete!